dataframe:
  train_size: 0.8
  shuffle: True
  target_column: null # if null, the last column will be used as a target
  drop_columns: null # list or null

experiment:
  model: KNNModel

knnmodel:
  n_neighbors: 5
  weights: 'uniform'
  algorithm: 'auto'
  leaf_size: 30
  p: 2
  metric: 'minkowski'
  metric_params: null
  n_jobs: null

rfcmodel:
  n_estimators: 100
  criterion: 'gini'
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: 'auto'
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  min_impurity_split: null
  bootstrap: True
  oob_score: False
  n_jobs: null
  random_state: null
  verbose: 0
  warm_start: False
  class_weight: null
  ccp_alpha: 0.0
  max_samples: null
